### ISSUE TITLE
Warning in HA 2023.2.0: async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by GerdRuetten** [mampfes/hacs_dwd_pollenflug#12] opened 2023-02-02 16:45 UTC
After update on HA 2023.2.0 i get following warning:

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for dwd_pollenflug using this method at custom_components/dwd_pollenflug/__init__.py, line 36: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by mampfes** [comment] 2023-02-02 18:29
duplicate of #11

**Closed by mampfes** 2023-02-02 18:29 UTC
